language: java
os: linux
jdk:
  - openjdk11
  - openjdk-ea
services:
  - docker
cache:
  directories:
    - $HOME/.m2
script:
  - ./mvnw --settings .maven.xml clean package -B
#after_success:
#  mvn --settings .maven.xml docker:build docker:push