language: java
jdk: openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
script:
  - ./mvnw --settings .maven.xml clean package -B
#after_success:
#  mvn --settings .maven.xml docker:build docker:push