language: java
os: linux
jdk:
  - openjdk12
services:
  - docker
cache:
  directories:
    - $HOME/.m2
install: false
script:
  - ./mvnw --settings .maven.xml clean package -B docker:build docker:push
#after_success:
#  mvn --settings .maven.xml docker:build docker:push