language: java
jdk: openjdk11
install:
  mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V docker:build docker:push -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD