version: '3.8'
services:
  filebeat:
    image: shreeshasa/filebeat:1.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    extra_hosts:
      - "elasticsearch:206.189.136.238"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  inventory-service:
    image: shreeshasa/mssc-beer-inventory-service #Set version if needed, keep in mind 'latest' tag will only be pulled the first time, updates will not automatically get pulled
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: digital-ocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.95.163:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"inventory-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"user","password":"password"}}},"application":{"name":"inventory-service"}}'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  inventory-failover-service:
    image: shreeshasa/mssc-inventory-failover-service
    ports:
      - 8083:8083
    environment:
      SPRING_PROFILES_ACTIVE: digital-ocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.95.163:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"inventory-failover-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"user","password":"password"}}},"application":{"name":"inventory-failover-service"}}'
    deploy:
      replicas: 2
  beer-service:
    image: shreeshasa/mssc-beer-service
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: digital-ocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.95.163:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"beer-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"user","password":"password"}}},"application":{"name":"beer-service"}}'
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  order-service:
    image: shreeshasa/mssc-beer-order-service
    ports:
      - 8084:8084
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: digital-ocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.95.163:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"order-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"brewery-config"},"failFast":true,"username":"user","password":"password"}}},"application":{"name":"order-service"}}'
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8080
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  gateway:
    image: shreeshasa/mssc-brewery-gateway
    ports:
      - 9090:9090
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: digital-ocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.95.163:8761/eureka/"},"region":"default","register-with-eureka":false},"instance":{"preferIpAddress":true}}}'
      SPRING_ZIPKIN_BASEURL: http://139.59.68.184:9411
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2